[versions]
# libraries
annotations = "24.1.0"
ddPlist = "1.27"
gradleIdeaExt = "1.1.7"
intellijStructure = "3.265"
intellijPluginRepositoryRestClient = "2.0.38"
jacksonDatabind = "2.16.0"
jaxbApi = "2.4.0-b180830.0359"
kotlinxSerializationJson = "1.6.2"
retrofit = "2.9.0"

# plugins
dokka = "1.9.10"
gradlePluginPublish = "1.2.1"
gradleChangelogPlugin = "2.2.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
ddPlist = { group = "com.googlecode.plist", name = "dd-plist", version.ref = "ddPlist" }
gradleIdeaExt = { group = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext", name = "gradle-idea-ext", version.ref = "gradleIdeaExt" }
intellijPluginRepositoryRestClient = { group = "org.jetbrains.intellij", name = "plugin-repository-rest-client", version.ref = "intellijPluginRepositoryRestClient" }
intellijStructureBase = { group = "org.jetbrains.intellij.plugins", name = "structure-base", version.ref = "intellijStructure" }
intellijStructureIntellij = { group = "org.jetbrains.intellij.plugins", name = "structure-intellij", version.ref = "intellijStructure" }
jacksonDatabind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jacksonDatabind" }
jaxbApi = { group = "javax.xml.bind", name = "jaxb-api", version.ref = "jaxbApi" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
