name: Initialise JVM + Gradle
description: Checkout and prepare the project for executing a Gradle task

runs:
  using: composite
  steps:

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false
