name: Build
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [master]
    paths-ignore: ['**.md', '.teamcity/**']
  # Trigger the workflow on any pull request
  pull_request:
    paths-ignore: ['**.md', '.teamcity/**']


# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  XDG_CACHE_HOME: "/home/runner/.cache/"

jobs:

  unitTests:
    name: Unit Tests
    uses: ./.github/workflows/reusable-unitTests.yml
