name: Release
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:

  # Run reusable test workflow
  test:
    name: Test
    uses: JetBrains/gradle-intellij-plugin/.github/workflows/reusable-test.yml@test-reusable-workflow

  # Prepare and publish the Gradle Plugins repository
  release:
    name: Release to Gradle Plugins
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.release.tag_name }}

      # Setup Java 8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
          cache: gradle

      # Publish the plugin to the Gradle Plugins
      - name: Publish Plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publish -Dsnapshot=true -DossrhUsername=$OSSRH_USERNAME -DossrhPassword=$OSSRH_PASSWORD

      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./build/libs/*
