name: Reusable Unit Tests

on: [ workflow_call ]

env:
  XDG_CACHE_HOME: "~/.cache/"

jobs:
  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - 7.5.1
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache XDG_CACHE_HOME
        uses: actions/cache@v3
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: ${{ runner.os }}-XDG_CACHE_HOME-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-XDG_CACHE_HOME-

      - name: Run Tests
        run: ./gradlew check -PtestGradleVersion="${{ matrix.gradleVersion }}" ${{ runner.os == 'Windows' && '-PtestGradleUserHome="C:\\testGradleHome"' || '' }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Unit Tests / Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }} / Report
          path: "**/build/test-results/*/TEST-*.xml"
          reporter: java-junit
