name: Reusable test workflow

on: [ workflow_call ]

env:
  XDG_CACHE_HOME: "~/.config/"

jobs:
  codeInspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.2.1
