name: Reusable Unit Tests

on: [ workflow_call ]

env:
  XDG_CACHE_HOME: "~/.config/"

jobs:
  baseUnitTest:
    name: Gradle 7.5.1 @ windows-latest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: 7.5.1
      os: windows-latest

  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    needs: baseUnitTest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: ${{ matrix.gradleVersion }}
      os: ${{ matrix.os }}
      script: ${{ matrix.script }}

    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - 6.8
          - 6.9.3
          - 7.5.1
          - 7.6-rc-3
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            script: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf /usr/local/lib/android
              sudo rm -rf /opt/ghc
        exclude:
          - os: windows-latest
            gradleVersion: 7.5.1
