name: Reusable Integration Tests

on:
  workflow_call:
    inputs:
      platformVersion:
        required: false
        default: 2022.1.4
        type: string

env:
  XDG_CACHE_HOME: "~/.config/"

jobs:
  subtasksList:
    name: Prepare Environment
    runs-on: ubuntu-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache XDG_CACHE_HOME
        uses: actions/cache@v3
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: ${{ runner.os }}-XDG_CACHE_HOME-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-XDG_CACHE_HOME-

      - name: Build and Publish Plugin to MavenLocal
        run: ./gradlew -Pversion="0.0.0" :publishToMavenLocal

      - name: Store Built Plugin
        uses: actions/upload-artifact@v3
        with:
          name: m2-repository
          path: ~/.m2/repository

  integrationTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    needs: subtasksList
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - 6.8
          - 6.9.3
          - 7.5.1
          - 7.6-rc-3
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Cache XDG_CACHE_HOME
        uses: actions/cache@v3
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: ${{ runner.os }}-XDG_CACHE_HOME-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-XDG_CACHE_HOME-

      - uses: actions/download-artifact@v3
        with:
          name: m2-repository
          path: ~/.m2/repository

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradleVersion }}

      # INTEGRATION TESTS

      - name: classpath
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./classpath/verify.main.kts `which gradle`
