name: Reusable Unit Tests

on: [ workflow_call ]

jobs:
  baseUnitTest:
    name: Gradle 8.1.1 @ ubuntu-latest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: "8.1.1"
      os: ubuntu-latest
      script: |
        mkdir /tmp/empty_dir
        sudo rsync -a --delete /tmp/empty_dir/ /usr/share/dotnet
        sudo rsync -a --delete /tmp/empty_dir/ /usr/local/lib/android
        sudo rsync -a --delete /tmp/empty_dir/ /opt/ghc
        rmdir /tmp/empty_dir

  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    needs: baseUnitTest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: ${{ matrix.gradleVersion }}
      os: ${{ matrix.os }}
      script: ${{ matrix.script }}

    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - "7.6"
          - "8.1.1"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            script: |
              mkdir /tmp/empty_dir
              sudo rsync -a --delete /tmp/empty_dir/ /usr/share/dotnet
              sudo rsync -a --delete /tmp/empty_dir/ /usr/local/lib/android
              sudo rsync -a --delete /tmp/empty_dir/ /opt/ghc
              rmdir /tmp/empty_dir
        exclude:
          - os: ubuntu-latest
            gradleVersion: "8.1.1"
