name: Reusable test workflow

on: [workflow_call]

jobs:
  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - 6.7.1
          - 6.9.2
          - 7.5.1
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            script: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf /usr/local/lib/android
              sudo rm -rf /opt/ghc

    steps:

      - name: Run OS-dedicated script
        if: ${{ matrix.script }}
        run: ${{ matrix.script }}

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Init Java + Gradle
        uses: ./github/actions/init-jvm-gradle

      - name: Run Tests
        run: ./gradlew check -PtestGradleVersion="${{ matrix.gradleVersion }}" ${{ runner.os == 'Windows' && '-PtestGradleUserHome="C:\\testGradleHome"' || '' }}

      - name: Collect Test Results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.gradleVersion }}-${{ runner.os }}
          path: ${{ github.workspace }}/build/reports/tests
