name: Reusable Unit Tests

on: [ workflow_call ]

env:
  XDG_CACHE_HOME: "~/.config/"

jobs:
  baseUnitTest:
    name: Gradle 7.5.1 @ windows-latest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: 7.5.1
      os: windows-latest
